services:
  anythingllm-dev:
    image: mintplexlabs/anythingllm:master
    container_name: anythingllm-dev    
    ports:
      - "3005:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=CWzny5S4x0LVp/vvTUBd85yPtzlMCORhJA32WenajRw=
    volumes:
      - /home/ajay/apps/anythingllm/storage:/app/server/storage
      - ./.env.dev:/app/server/.env
    restart: unless-stopped

  anythingllm-prod:
    image: mintplexlabs/anythingllm:latest
    container_name: anythingllm-prod
    ports:
      - "3007:3001"
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=DBSJlxYygB9mtT2uLM9TYK+/tlTcfwY49/K4aZ6UaMc=
    volumes:
      - /home/ajay/apps/anythingllm-prod/storage:/app/server/storage
      - ./.env.prod:/app/server/.env
    restart: unless-stopped